### ISSUE TITLE
ER diagramm and database

### ISSUE THREAD

**Issue by hannesbaum** [hannesbaum/ATdIT_Gruppe1#3]
ER-diagramm, database implementation etc.

**Comment by hannesbaum** [comment]
**Kardinalitäten**
_apartment-propManagement:_ n:1
_apartment-customer_ 1:1 (** wir wissen, dass zwar mehrere leute in einer Wohnung wohnen können, aber uns genügt es, eine Kontaktperson zu haben**)
_apartment-region_: n:1
_apartment-readingHistory_ 1:n
_apartment-appointment_ 1:n **( da man die Termine nicht so bald löscht, um sie im Nachhineien nochmal einsehen zu können, einen neuen termin anzusetzen etc**)

_appointment-task:_ 1:n **( ein Termin kann mehrere Aufgabenklassen haben, z.B. wenn wir sagen, dass x Zähler von einem Typ, y Zähler eines anderen Typen montiert werden sowie alle Zähler abgelesen werden-> das wären dann 3 Aufgabenklassen. 
Unsere Klassen: a)nur Montage, b) nur Ablesen, c) Autausch(Demontage und Montage), d) a+b, e) a+c )**

_appointment-staff:_ n:1 (**auch möglich n:m, aber wir interpretieren das eben so, dass hier der hauptverantwortliche Mitarbeiter drin steht**)

_staff-region_ n:m (da wir die Größe der Bezirke sehr variabel halten möchten, kann sowohl 1 Mitarbeiter mehrere Bezirke abdecken als auch ein Bezirk von mehreren Mitarbeitern "beackert" werden)

_appointment - deviceUnit_ 1: n
_deviceUnit-deviceType_ n:1
_ReadingHistory-staff_ n:1

**Comment by hannesbaum** [comment]
[VersuchNach0516.pdf](https://github.com/hannesbaum/ATdIT_Gruppe1/files/2014632/VersuchNach0516.pdf)

**Comment by hannesbaum** [comment]
**Zum heutigen Upload von VersuchNach0516: ** 
Mit Sicherheit einen Schritt besser: 
1) neue Entität Wohnung an der Stelle, wo vorher Mieter war. 
2) Mieter enthält nur noch Kontaktdaten
3) Kardinalitäten (tw) gecheckt
4) Attribut Anzahl der Zähler von Entität Bezirk weg (stattdessen Attribut NrZaehler bei Wohnung)
[22:36, 17/5/2018] Hannes ;): 5) Verbindung Termin-Exemplar und nicht Termin-Typ
durch 1) ist nun ein Wert der Wohnung und dem Zähler und nicht dem Mieter zugeordnet.

**Comment by hannesbaum** [comment]
**UPDATE: dies ist nicht  mehr der aktuelle Stand. Für die aktuellen Datentypen, siehe weiter unten** 

@mischhh
**Zu den Datentypen: **
WOHNUNG: 
Wohnung_ID: INT
PLZ: INT
Ort, Strasse: VARCHAR(50)
Adresszusatz: VARCHAR(400)
Hausnummer, NrZaehler: SMALLINT

HAUSVERWALTUNG: 
Verwaltung_ID: INT
Firmenname, Mail, Ansprechpartner: VARCHAR(50)
offeneGebuehren: INT
Telefon: VARCHAR(50) **kann kein Int sein, da mit Int weder "+49" noch "0049" möglich, da am Beginn keine Null sein darf**
Faelligkeit: DATE 

TERMIN: 
Termin_ID: INT
Datum: DATE
Uhrzeit_von, Uhrzeit_bis: TIME
Mietermeldung: VARCHAR(600)
Termin_wahrgenommen: BIT(1)
wievielter_Termin, Status: SMALLINT  (**Erklärung zu Status siehe unten)**

AUFGABEN:
Aufgabenklasse: INT
Beschreibung:VARCHAR(200) (**z.B: "Ablesen" oder "Austausch" oder "Neumontage"** )
Preis: NUMERIC(6,2)
Zeitansatz: SMALLINT **Zeit in Minuten**
Material: VARCHAR(100) **(dazu da, dass der Mitarbeiter weiß, welches Equipment er ins Auto packt)**


MITARBEITER: 
Empl_ID: VARCHAR(30)
Vorname, Nachname,AutoKennzeichen, Ort, Strasse: VARCHAR(50)
PLZ: INT
GebDatum: DATE
Fuehrerscheinklasse: VARCHAR(20) **in DE würden weniger Zeichen langen, i.d.R 2 für z.B. CE, aber der 
Einfachkeit halber, um alte Führerscheine etc nicht auszuschließen, lassen wir hier Spielraum**

BEZIRK: 
Bezirksname: VARCHAR(50) **ansonsten haben wir immer davon abgesehen, einen Namen als Schlüssel zu verwenden. Bei Bezirken finden wir es aber als vertretbar; im Zweifelsfall eben "Ber_Mitte1, Ber_Mitte2 etc**
N_Haushalte: INT

ABLESEHISTORY: 
Ablesung_ID: INT  (**Schlüssel aus Datum sowie den Fremdschlüsseln Wohnung_ID und Exemplar_ID wäre denkbar(da eindeutig und minimal), aber umständlich zu handhaben und außerdem schwer im ER-Diagramm darzustellen**
Ablesedatum, Stichtagsdatum: DATE
Zaehlerstand_aktuell, Zaehlerstand_Stichtag: INT
Pruefzahl: VARCHAR(30)
Anzeigest: VARCHAR(2) (**Erklärung zu Pruefzal und Anzeigetest unten**)

bezahlt: BIT(1)

ZAEHLEREXEMPLAR: 
Exemplar_ID : INT
montiert_am: DATE

ZAEHLERTYP: 
Typ_ID: VARCHAR(50) **hier ergibt es Sinn, die Typenkennung der Hersteller zu übernehmen. Da diese ggf auch Zeichen/Bindestriche etc enthält, nehmen wir hier keinen INT**
Bezeichnung: VARCHAR(50)
Funk: BIT(1)

MIETER: 
Mieter_ID: INT
Vorname, Nachname, Mail, Festnetz, mobil: VARCHAR(50)

**Comment by hannesbaum** [comment]
**Erklärungen zu manchen Entitäten&Attributen**: 
**propManagement (= Hausverwaltung):** 
klar wäre hier denkbar, dass man Telefon und Mail in eine weitere Entität "contactPerson" auslagert. Da die Kommunikation mit der Hausverwaltung jedoch nicht unser primärer Scope ist, haben wir der Einfachheit halber darauf verzichtet.

- Faelligkeit gibt an, bis wann die Zahlung an unser Unternehmen zu tätigen ist. 

**apartment:** 
counterNr: Anzahl der Zähler; wird erst richtig relevant mit der Preisberechnung zusammen mit dem Preis pro Aufgabenklasse aus AUFGABE. Preis = Preis(aus Aufgabe)*Aufgabenklasse*NrZaehler

- Adresszusatz: z.B. "zweites OG rechts"

**readingHistory**
pro Ablesevorgang und pro Zähler ein eigener Datensatz. Wir löschen die letzten Werte nicht aus der DB, insofern gibt es da mit der Zeit pro Zähler etliche Datensätze. 

- es wird immer der Zählerstand zum Stichtag (in der Vergangenheit) und zum aktuellen Datum abgelesen. 

- Pruefzahl: Sie ist vor allem für das zuständige Abrechnungsunternehmen wichtig. Mit ihr lässt sich die Richtigkeit des aktuellen Verbrauchswertes überprüfen. Die Prüfzahl wird auch als Checkzahl bezeichnet und dementsprechend auf dem Display des elektronischen Heizkostenverteilers durch ein „C“ eingeleitet.
( Quelle: https://www.talu.de/heizung-richtig-ablesen/  )

- Anzeigetest: Er ist an den untereinander stehenden Buchstaben „M“ und „C“ erkennbar und dient dazu, Ihnen zu demonstrieren, dass die Anzeige keinen Defekt hat.
( https://www.talu.de/heizung-richtig-ablesen/  )

**customer (der Mieter):** 
uns reicht es aus, die Daten eines Mieters zu kennen zwecks Festnetznummer(die ist ohnehin für alle gleich) und noch einer Handynummer &Mail sowie ggf. geschäftlicher Mail und Telefon. 


**appointment**
_Status_: wo dann gespeichert werden kann:
muss der Termin noch datiert werden?
warten wir auf eine Kundenbestätigung des Termins?
ist der Termin "aktiv" und kann abgearbeitet werden?
ist der Termin wahrgenommen worden und liegt somit in der Vergangenheit? (ist ein Int-Wert; den Rest macht das Backend)
-wievielter Termin ist relevant,
-in Mietermeldung stehen Texte, die der Mieter mitgeteilt hat (z.B. Beschreibung eines Problems o. Ä. ) 

**region**
numberApartments(Nummer der Haushalte im Bezirk) : dient weniger unserem Szenario für die App als vielmehr der Firma allgemein als Grundlage zum Organisieren.

**Comment by hannesbaum** [comment]
[VersuchNach0516.pdf](https://github.com/hannesbaum/ATdIT_Gruppe1/files/2018559/VersuchNach0516.pdf)

**Comment by hannesbaum** [comment]
[VersuchNach0516.pdf](https://github.com/hannesbaum/ATdIT_Gruppe1/files/2019364/VersuchNach0516.pdf)

**Neues zur Vorgänger-Version:**
1) künstl. Primärschlüssel Ablesung_ID bei der Ablesehistory
2) Attribut "Beschreibung" bei AUFGABE
3)überall Zaehlerstand statt Zaehlerstand/und ZAEHLERTYP/-EXEMPLAR statt ZÄHLERTYP/-EXEMPLAR

**Comment by hannesbaum** [comment]
[VersuchNach0516.pdf](https://github.com/hannesbaum/ATdIT_Gruppe1/files/2019374/VersuchNach0516.pdf)
**Neues zur Vorgänger-Version:**
1) künstl. Primärschlüssel Ablesung_ID bei der Ablesehistory
2) Attribut "Beschreibung" bei AUFGABE
3)überall Zaehlerstand statt Zaehlerstand/und ZAEHLERTYP/-EXEMPLAR statt ZÄHLERTYP/-EXEMPLAR 
4) Kardinalität Wohnng-Termin 1:n

**Comment by hannesbaum** [comment]
**Neues zur Vorgänger-Version:**
    künstl. Primärschlüssel Ablesung_ID bei der Ablesehistory
    Attribut "Beschreibung" bei AUFGABE
    3)überall Zaehlerstand statt Zaehlerstand/und ZAEHLERTYP/-EXEMPLAR statt ZÄHLERTYP/-EXEMPLAR
    Kardinalität Wohnng-Termin 1:n
4) Kardinalität Termin-Aufgabenklasse 1:n
[VersuchNach0516.pdf](https://github.com/hannesbaum/ATdIT_Gruppe1/files/2019504/VersuchNach0516.pdf)

**Comment by hannesbaum** [comment]
[VersuchNach0516.pdf](https://github.com/hannesbaum/ATdIT_Gruppe1/files/2019512/VersuchNach0516.pdf)
Rechtschreibfehler beseitigt

**Comment by hannesbaum** [comment]
[VersuchNach0516.pdf](https://github.com/hannesbaum/ATdIT_Gruppe1/files/2019563/VersuchNach0516.pdf)

"Adresszusatz" bei Wohnung sowie "Pruefzahl" und "Anzeigetest" bei Ablesehistory hinzugekommen.

**Comment by 19marsi97** [comment]
@hannesbaum 
ich habe dann mal die DB gebaut mit Miris Ansatz.
Hier nochmal alle Datentypen, es wäre super wenn du auch nochmal drüberguckst ob ich nicht irgendwas in der Logik verpennt habe!
Achso, es existiert ein Datentyp "TEXT" welchen ich dann für alle Textattribute verwendet habe!

**Hausverwaltung** (propManagement = propertyManagement)
manageId (TEXT); Primärschlüssel
email (TEXT)
phone (TEXT)
contactPerson (TEXT) -> hiermit ist ein Ansprechpartner gemeint, oder? also ein Name?
charges (TEXT) -> Grund für Text: so kann man kommazahlen sinnvoll trennen ;)
companyName (TEXT)

**Wohnung** (apartment)
apartmentId (TEXT); Primärschlüssel
address (TEXT) -> Straße und Hausnummer sind hier zusammengefasst
addition (TEXT) -> Adresszusatz
zip (INTEGER) -> PLZ (sollte mit Zahl denkbar sein, oder?)
city (TEXT)
counterNr (INTEGER) -> Anzahl der Zähler pro Wohnung
manageId (TEXT); Fremdschlüssel
customerId (TEXT); Fremdschlüssel

**Kunde** (Customer)
customerId (TEXT); Primärschlüssel
firstName (TEXT)
lastName (TEXT)
phone (TEXT)
email (TEXT)
mobile (TEXT)
phoneBusi (TEXT) -> hab ich einfach aus dem App-Layout noch übernommen
emailBusi (TEXT) -> hab ich einfach aus dem App-Layout noch übernommen
apartmentId (TEXT); Fremdschlüssel

**Zählerexemplar** (deviceUnit)
deviceId (TEXT); Primärschlüssel
installedDate (TEXT)
apartmentId (TEXT); Fremdschlüssel
typeId (TEXT); Fremdschlüssel

**Zählertyp** (deviceType)
typeId (TEXT); Primärschlüssel
name (TEXT)
funk (INTEGER) -> 0 für nein; 1 für ja

**Mitarbeiter** (staff)
staffId (TEXT); Primärschlüssel
firstName (TEXT)
lastName (TEXT)
licencePlate (TEXT)
driverId (TEXT)
address (TEXT)
city (TEXT)
zip (TEXT)
birthday (TEXT)

**Ablesehistory** (readingHistory
readingId (TEXT); Primärschlüssel
readingDate (TEXT)
countNow (INTEGER)
countDueDate (INTEGER)
dueDate (TEXT)
payed (INTEGER) -> 0 = nein; 1 = ja
checkSum (TEXT)
deviceTest (TEXT)
deviceId (TEXT); Fremdschlüssel
staffId (TEXT); Fremdschlüssel

**Bezirk** (region)
name (TEXT); Primärschlüssel
numberApartments (TEXT)

**Empl_Bezirk** (staffRegion)
staffId (TEXT); Fremdschlüssel; Primärschlüssel
regionName (TEXT); Fremdschlüssel; Primärschlüssel

**Aufgaben** (task)
taskId (TEXT); Primärschlüssel
price (TEXT)
description (TEXT)
material (TEXT)
taskTime (INTEGER NOT NULL)

**Termin** (appointment)
appointmentId (TEXT); Primärschlüssel
status (INTEGER)
date (TEXT)
startTime (TEXT)
endTime (TEXT)
taskId (TEXT); Fremdschlüssel
customerNotes (TEXT)
count (INTEGER) -> beinhaltet, der wievielte Termin es ist. Ist notwendig, da man verpflichtet ist, einen Zweittermin zu vergeben (falls der Mieter nicht da war), aber anstelle eines 3.Termins das Recht hat, den Verbrauch zu schätzen (siehe https://www.sat1.de/ratgeber/finanzen-recht/recht/heizungsableser-clip )
aptId (TEXT); Fremdschlüssel (apartmentId)
staffId (TEXT); Fremdschlüssel

**Comment by hannesbaum** [comment]
[VersuchNach0516_englisch.pdf](https://github.com/hannesbaum/ATdIT_Gruppe1/files/2020412/VersuchNach0516_englisch.pdf)
**Updates:** 
alles nun auf English
Verbindung Exemplar-termin gelöscht. 
@mischhh @19marsi97 : dueDate (bei propManagement) und appointmentAttended (bei Termin)  fehlen in eurer DB!

**Comment by hannesbaum** [comment]
![er_diagramm_gruppe1_final](https://user-images.githubusercontent.com/37547972/40386015-dc99280c-5e08-11e8-8e89-478c213af25a.png)

**Comment by hannesbaum** [comment]
![er_diagramm_gruppe1_final_hoheauflosung](https://user-images.githubusercontent.com/37547972/40575098-934e4622-60de-11e8-99f5-4c6ad2885a44.png)
**Umbennennung der Emp_ID zur staffId gemäß unserer DB**

**Comment by hannesbaum** [comment]
[Normalformanalyse unseres Datenbank_Gruppe1.docx](https://github.com/hannesbaum/ATdIT_Gruppe1/files/2042641/Normalformanalyse.unseres.Datenbank_Gruppe1.docx)
zeigt, dass sich unsere DB in der dritten Normalform nach Boyce-Codd befindet.

**Comment by hannesbaum** [comment]
[Normalformanalyse unseres Datenbank_Gruppe1.docx](https://github.com/hannesbaum/ATdIT_Gruppe1/files/2042684/Normalformanalyse.unseres.Datenbank_Gruppe1.docx)

zeigt, dass sich unsere DB in der dritten Normalform nach Boyce-Codd befindet.

**Comment by hannesbaum** [comment]
[Normalformanalyse unseres Datenbank_Gruppe1.docx](https://github.com/hannesbaum/ATdIT_Gruppe1/files/2045690/Normalformanalyse.unseres.Datenbank_Gruppe1.docx)
updated version
