### ISSUE TITLE
Datenbank Beispieldaten

### ISSUE THREAD

**Issue by 19marsi97** [hannesbaum/ATdIT_Gruppe1#7]
Heyo!

erstmal nochmal danke an Miri für die Datenbanktabellen. Ich habe nochmal ein bisschen dran rumgebastelt und die letzten Fremdschlüsselbeziehungen sowie alle Datentypen ergänzt.

@hannesbaum : Der Entwurf müsste nun zu 95% dem ER-Diagramm entsprechen; ich habe halt so Sachen wie Straße und Hausnummer in ein Feld getan. Hoffentlich kannst du damit leben! :)

@ **Miri**: Es wäre super, wenn du noch ein paar Beispieldaten für die Datenbank erstellen könntest. 
Guck dir mal diese Datei an: "Server_2018-05-20.zip\ATdIT_Projekt\src\Projekt_Server\CreateDB2.java" 
Da sind schon viele Beispiele vorgegeben und angedacht. Wir bräuchten insbesondere noch mehrere Einträge bei Wohnungen, Kunden/Mietern und Terminen. Dabei kannst du deiner Kreativität freien Lauf lassen. 
Bitte beachte nur folgende Rahmenbedingungen:
-> Die Termine sollten von Datum her im Mai oder Juni sein (keine Samstage/Sonntage)
-> Die Termine sollten zwischen 9:00 Uhr und 16:30 Uhr liegen
-> Als "status" ist bei Terminen erstmal nur 0 oder 2 erlaubt

Es wäre cool, wenn du die neuen Werte bis Mitte nächster Woche hinbekommst, dann lasse ich die nochmal im Programm laufen und gucke mir das Ergebnis an! :)

**Comment by mischhh** [comment]
@19marsi97 bin dabei, sodass wir am Ende 15 Personen haben. Sollte ich heute noch hochladen können :)

**Comment by mischhh** [comment]
@19marsi97 guck mal ob dir das so passt :)
