### ISSUE TITLE
PowerPoint Präsentation

### ISSUE THREAD

**Issue by 19marsi97** [hannesbaum/ATdIT_Gruppe1#8]
Servus!
Ich mache einfach nochmal nen Issue auf, wo dann alles zum Thema Präsentation reinkommt.

Jeder sollte sich vllt ein paar Gedanken machen, was er wie präsentiert und dabei unbedingt auf die Zeit achten. 
Denkt dran, bis Freitag (da treffen wir uns morgens) sollte die PPT größtenteils stehen! 

Ich gehe davon aus, dass das nicht zu viel Arbeit wird. 
Ich werde heute noch ein PPT-Template hochladen, sodass wir nicht alle mit einem unterschiedlichen Layout arbeiten :)

**Comment by 19marsi97** [comment]
[PPT Tips](http://www.garrreynolds.com/preso-tips/design/)

Ich gehe bei der PPT Erstellung oft nach solchen Tipps vor. Vielleicht helfen euch die auch ein bisschen!

**Comment by hannesbaum** [comment]
@19marsi97 @mischhh 
[Persona.pptx](https://github.com/hannesbaum/ATdIT_Gruppe1/files/2028253/Persona.pptx)
**Updates:  Rechtschreibkorrekturen sowie kleine Ergänzungen; **
Fragen: 1) gehen wir nun davon aus, dass er Mitarbeiter hat, richtig? (ich habe das "ggf" bei Mitarbeiter entfernt. )
2) schickt unsere Persona selbst die Sachen an die Hausverwaltung? Sprich: unsere Persona ist der Chef, richtig?

**Comment by hannesbaum** [comment]
![image](https://user-images.githubusercontent.com/37547972/40385766-f9065916-5e07-11e8-9e5b-4703b7db192c.png)
ER-Diagramm rangezoomt an Entität apartment

**Comment by hannesbaum** [comment]
![er-diagramm_ramgezoomt_apartment](https://user-images.githubusercontent.com/37547972/40385882-53b6f8fc-5e08-11e8-9a7c-a20d77cf0e57.png)

**Comment by hannesbaum** [comment]
![er-diagramm_ramgezoomt_appointment](https://user-images.githubusercontent.com/37547972/40385914-79b9d790-5e08-11e8-827d-c5694c96fea2.png)

**Comment by hannesbaum** [comment]
für Änderungen an der Powerpoint bitte über den Link von Simon in der Online Powerpoint arbeiten.
Nochmals hier der Link: 
https://sap-my.sharepoint.com/:p:/r/personal/simon_martin_sap_com/Documents/ATdIT%20Presentation_2.pptx?d=w92c356c53e644d0ead5559eed2a62756&csf=1&e=uRc68w
