### ISSUE TITLE
Server backend:Verschiedene Views für DB Zugriff

### ISSUE THREAD

**Issue by 19marsi97** [hannesbaum/ATdIT_Gruppe1#9]
@hannesbaum : Hier dein Issue für das Backend

Nun die überarbeitete Version! :)

Miri hat schon eine sehr aktuelle Version der DB Daten in das Github hochgeladen.
Anhand der Tabellen und Daten wäre es sinnvoll, falls wir zwei verschiedene Views auf die Datenbanken erstellen (so wie in Melchers Vorlesung). 

Eine davon sollte nur für unseren Chef zur Verfügung stehen und die andere für alle Mitarbeiter.
Erstelle zudem für jede View die entsprechenden Zugriffsrechte; Mitarbeiter dürfen beispielsweise nicht die Entitäten "Kunden", "Wohnungen", etc. bearbeiten sondern nur lesen.

Erstelle auch für jede View ein Passwort, sodass der Zugriff entsprechend über den Server geleitet werden kann.

**Comment by hannesbaum** [comment]
[v1_View+User.txt](https://github.com/hannesbaum/ATdIT_Gruppe1/files/2041751/v1_View.User.txt)
**erster Entwurf zur Implementierung zweier Benutzer mit verschiedenen Rechten und dazu passend die Sicht (View) für den "einfachen Mitarbeiter" , hier noch syntaktisch als CROSS JOIN mit Bedingungen**

**Comment by hannesbaum** [comment]
[v1_View+User.txt](https://github.com/hannesbaum/ATdIT_Gruppe1/files/2041773/v1_View.User.txt)
**erster Entwurf zur Implementierung zweier Benutzer mit verschiedenen Rechten und dazu passend die Sicht (View) für den "einfachen Mitarbeiter" , hier noch syntaktisch als CROSS JOIN mit Bedingungen**

**Comment by hannesbaum** [comment]
[v2_View+User_alsINNERJOIN.txt](https://github.com/hannesbaum/ATdIT_Gruppe1/files/2041776/v2_View.User_alsINNERJOIN.txt)
**Anmerkung (so auch nochmal in der Datei als Kommentar vorzufinden) :**  Diese Datei soll aufzeigen, wie wir in unserer DB (und somit unserer App) differenzieren wollen bzgl. verschiedener Benutzer mit unterschiedlichen Rechten. 
 Allerdings ist in der von uns benutzten RDBMS SQLite weder die Verwaltung von Benutzer-und Zugriffsberechtigungen möglich noch unterstützt sie Views
 (siehe https://sqlite.org/omitted.html  und https://www.wikiwand.com/de/SQLite  ).
 Insofern bleibt es hier bei der Idee (mit den passenden SQL-Befehlen für eine andere RDBMS, die das unterstützt) . 
 
 Wir haben: 2 Benutzer, einen für den Chef sowie einen für die Angestellten. 
 Der Chef darf alles; die Mitarbeiter haben nur Zugriff auf die View, die die Relationen propManagement (Hausverwaltung) ,staff, staffRegion (Fremdschlüsseltabelle) sowie region
nicht beinhaltet. Außerdem  ist die Art des Zugriffs auf die Relationen der View wiederum abhängig von der einzelnen Relation (Begründungen als Kommentare neben den 
SQL-Befehlen ) */ 

--Tipp: in Notepad++ öffnen und unter "Sprachen" SQL auswählen -> highlighted die Syntax

**Comment by hannesbaum** [comment]
@19marsi97 : ich habe die View soweit fertig und mit Kommentaren dabei . Dazu habe ich die beiden Benutzer angelegt und ihnen die entsprechenden Rechte zugewiesen.
